### ISSUE TITLE
Bad Hash

### ISSUE THREAD

**Issue by gmorenz** [GodotVR/godot-openvr-asset#10]
Trying to install this asset through the editor results in the error message 

```
Asset Download Error:
Bad download hash, assuming file has been tampered with.
Expected: e4b0c4[...]
Got: 27a80[...]
```

(It won't let me cut and past the error message, so hashes manually copied and trunacted)

**Comment by BastiaanOlij** [comment]
There was an issue with the hash not being copied when the asset went live, so it was comparing it against an old hash. It should be corrected now.
