### ISSUE TITLE
A file depends on vr-common, but this isn't included in the documentation

### ISSUE THREAD

**Issue by aaronfranke** [GodotVR/godot-openvr-asset#12]
The [setting up a basic project](https://github.com/GodotVR/godot-openvr-asset/wiki/Setting-up-a-basic-project) documentation does not include downloading the "vr-common" folder, but `scenes/ovr_first_person.tscn` depends on it. Trying to open gives this:

```
 Cannot open file 'res://addons/vr-common/misc/VR_Common_Shader_Cache.tscn'.
 Failed loading resource: res://addons/vr-common/misc/VR_Common_Shader_Cache.tscn.
```

Is "vr-common" required? If so, it should be added to the documentation. If not, why does one of the files in this asset depend on it?

**Comment by BastiaanOlij** [comment]
No that is a mistake in the original library. Thanks for noticing that!

**Comment by TheConceptBoy** [comment]
This is still present in the library. Even if I Open Anyway, it fails to open the scene of the player.
