### ISSUE TITLE
Files are not in sync with source

### ISSUE THREAD

**Issue by aaronfranke** [GodotVR/godot-openvr-asset#13]
https://github.com/GodotVR/godot-openvr-asset/tree/master/addons/godot-openvr/scenes

https://github.com/GodotVR/godot_openvr/tree/master/demo/addons/godot-openvr/scenes

I just spent some time trying to improve the assets in this repo. Then I discovered that their source is somewhere else. Then when I pasted them in, I discovered that the source files are different. Please sync them up, I have to throw away these (thankfully minor) changes now.

**Comment by BastiaanOlij** [comment]
Hi Aaron,

The files in godot_openvr are leading, they are only updated in this repository when we do an official release. This repository is what the Godot Asset Library accesses when people install the plugin so we don't want this updated until a new build is stable and tested
