### ISSUE TITLE
Direct users to VR controllers model implementation

### ISSUE THREAD

**Issue by patrykkalinowski** [GodotVR/godot-openvr-asset#14]
I have no idea how to make pull request for wiki as it's not editable, I figured out I'll write here.

I suggest adding new paragraph to https://github.com/GodotVR/godot-openvr-asset/wiki/Displaying-3D-controller-models:

> Implementation of VR controllers is created in `addons/godot-openvr/scenes/ovr_controller.tscn`. Use this scene as your ARVRController and it should work out of the box.

I found this by accident after several minutes of searching how to do it manually. I think it's worth to not hide the knowledge :)

**Comment by BastiaanOlij** [comment]
Thanks for the suggestion, sorry that I didn't see this issue until now. There is a git repo associated with the WIKI but I haven't found a way to do a PR workflow around that, I don't think github supports that.

Anyway I've worked it slightly differently and added a remark to point people to that scene. Good call! Thanks again :)
