### ISSUE TITLE
Displaying on screen but showing unresponsive in SteamVR

### ISSUE THREAD

**Issue by Logmytech** [GodotVR/godot-openvr-asset#7]
So, the demo displays fine on my monitor, but shows unresponsive in Steam VR.

The debugger shows that the FPS is above 1500 which is good, but as it is unresposive in Steam VR it's not working.

**Comment by BastiaanOlij** [comment]
Sounds like it is not sending output to steam vr. What version of Godot are you using? The asset only works with Godot 3.0.x, not with a build from master, you need to build the plugin build from source to work with 3.1

**Comment by Logmytech** [comment]
Sorry about this. It seems the project I chose was one of the old versions I downloaded from one of your youtube tutorilas or demos.

I tried another version and it works.
